### PR TITLE
Switch to the newer Google TTS API

### PR DESCRIPTION
**Pull request by Boudewijn26**
I couldn't for the life of me figure out where Translate is getting the list of languages from which it is able to TTS. Hopefully someone else can figure that out.

This solves #232

### CODE REVIEW

**Comment by mcv93us** [comment]
> I couldn't for the life of me figure out where Translate is getting the list of languages from which it is able to TTS. Hopefully someone else can figure that out.
> 
> This solves #232



> I couldn't for the life of me figure out where Translate is getting the list of languages from which it is able to TTS. Hopefully someone else can figure that out.
> 
> This solves #232

Hi, despite having updated the gTTS library and consequently also the gTTS-token, I keep crashing in a completely random way, if it works perfectly for me 3 times then it crashes for another 10!
Looking at the code, there was one thing I was wondering: in sending the user agent is there a specific reason why you should send such an ancient version of Chrome?

**Comment by marvin-w** [comment]
Did you use this PR or did you use the currently released version...?

**Comment by mcv93us** [comment]
> Did you use this PR or did you use the currently released version...?

I used the current released version.

**Comment by pndurette** [comment]
@Boudewijn26 Thanks! :D 
Looking at this tonight (GMT-5!)

**Comment by pndurette** [comment]
@mcv93us This PR should fix that. In the meantime, please follow #232!

**Comment by mcv93us** [comment]
> @mcv93us This PR should fix that. In the meantime, please follow #232!

Ok, thank you so much.

**Pull request merged**
