### PR TITLE
add 'country' option 

### PR DESCRIPTION
**Pull request by onsunsl**
Add 'country' option and then select TTS domain name by the 'country' option. This design for China user.

 > from gtts import gTTS
 >tts = gTTS('你好', lang='zh-cn', country='China')
 >tts.save('你好.mp3')

### CODE REVIEW

**Comment by pndurette** [comment]
Hi! First of all, all the tests are failing. Second, I'm supposing `translate.google.com` doesn't work in China `translate.google.cn` does? Interesting, I did not know that.

I see what you're trying to do and that's interesting if that fixes the issue, but I would rather see a unique place where the URL comes from, rather than `%`-formatting it all over the place.

**Comment by onsunsl** [comment]
The service provided by Google is not available in China, except for translation. If i change to https://translate.google.cn gtt can work.

**Comment by onsunsl** [comment]
Yes, I want format translat.google.cn by country option.

**Comment by pndurette** [comment]
I see the problem. I'm not keen on your `%`-formatting all over the place as stated above. I'd rather see a new module or util function or something to manage/retrieve the proper url in one single spot. Not just patch it all over the place. Otherwise I can work on it myself when I've got some time.

**Comment by pndurette** [comment]
Hi @onsunsl,

`gTTS` `2.1.0` now supports custom Google domains! In both the module and `gtts-cli`. In your case you can instruct it to use google.cn for all queries. 

Thanks for the idea, however I made this more generic for any Google domains without the concept of country and complex string formatting:

For the module:
```python
from gtts import gTTS tts = gTTS('你好', lang='zh-cn', tld='cn') tts.save('你好.mp3')

```

For the CLI:
```bash
gtts-cli --tld 'cn'  --lang 'zh-cn'  '你好' --output 你好.mp3
```

**Pull request closed without merging**
