### PR TITLE
Make gTTS work with Google's token system

### PR DESCRIPTION
**Pull request by Boudewijn26**
Made pull request to develop branch instead of master as per: https://github.com/pndurette/gTTS/pull/16

### CODE REVIEW

**Comment by Boudewijn26** [comment]
It appears the token key is the amount of hours from unix epoch. I'll try to fix something up using that info later this weekend.

**Comment by pndurette** [comment]
Great discovery re: calculating the token in-house. Looks good, I'll merge and release shortly. Thanks a lot @Boudewijn26!

**Comment by pndurette** [comment]
Thanks again for that submission, version `1.1.2` has been pushed to PyPy (had some deploy issues with TravisCI and PyPi doesn't allow you to re-upload a version anymore so burned a few).

**Comment by Boudewijn26** [comment]
Thank you for the clean up. I wonder how long before Google decides to switch it up and come up with a different token system.

**Comment by Boudewijn26** [comment]
Perhaps you can close #15 now?

**Pull request merged**
