### PR TITLE
merge master / #97, add AppVeyor (Windows self-test), dedupe / remove test race condition

### PR DESCRIPTION
**Pull request by scivision**
Also removed Python 3.3, which is [no longer supported/End of Life](https://www.python.org/dev/peps/pep-0398/#id21)

### CODE REVIEW

**Comment by pndurette** [comment]
Ah, this is great! Version `2.0.0.` should be Windows compatible (including the cli tool that requires bash in the current version). I'll poke around with AppVeyor soon. Thanks a lot for this file! (and the rest, too!)

**Comment by pndurette** [comment]
The files you have changed in `gtts/` have been modified a bit (I was working on this yesterday), but these are great little finds (e.g. using `assert`). I'll pull them in manually.

**Comment by scivision** [comment]
Yes important is the `with tempfile.SpooledTemporaryFile...` that's to avoid race conditions on Windows with very rapid creation-deletion of files during the self test.

Also one of the open issues was over UTF-8--this was enhanced in Python 3.6, and is enhanced more in Python 3.7, but there could be some corner cases seen only on Windows.

**Comment by scivision** [comment]
yep perhaps some UTF8 e.g. Cyrillic test input if you haven't already.

**Comment by pndurette** [comment]
Yeah, I do with some Chinese in [gtts/tests/test_tts_utils.py](https://github.com/pndurette/gTTS/blob/4cc4a012c3bad28164a57496e346fb404d80c735/gtts/tests/test_tts_utils.py#L67-L75) for the string processing tests. Also in the process of adding some various tests for the cli bit as well (stdin, command-line argument, read from file).

**Comment by scivision** [comment]
Yes that's it, the UTF8 needs to come from the command line to test fully UTF8.

**Pull request merged**
