### PR TITLE
Added utf-8 support to gtts-cli.py

### PR DESCRIPTION
**Pull request by bakaiadam**
My language has accent characters and with this modification, it works well. I guess the right way to do this would be a command line option for selecting file encoding, but my python knowledge is not good enough for that.

### CODE REVIEW

**Comment by pndurette** [comment]
Ohh, thank you for this @bakaiadam, I will look it shortly.

**Comment by bakaiadam** [comment]
Hello!
Is there any updates regarding the pull request?
Now I see that i made the change on the master branch, not the development branch. If that's an issue, i can redo it on the development branch,too.

**Comment by pndurette** [comment]
@bakaiadam Very sorry about this. I was away, then pretty sick.. I'm handling this now! Thanks!

**Comment by pndurette** [comment]
`gTTS` `1.1.7` deployed to PyPI!

**Pull request merged**
