### PR TITLE
Feature/cli using pipe

### PR DESCRIPTION
**Pull request by Dr-Horv**
Allow gtts-cli to default to using stdout to allow piping. Move output file to -o option.

### CODE REVIEW

**Comment by pndurette** [comment]
Oh sweet! Thanks @Dr-Horv! Sorry for the delay, this got lost in GitHub stuffs. Let me look at this ASAP.

**Comment by pndurette** [comment]
Sorry for the delay. Thanks a lot for this! :smile:

I can see how that can be useful for some to pipe into audio tools. And even though it's a 'breaking change' for the cli, your proposed way is more standard, so thank you.

A few things however:

* On the way you use `argparse`:
  * Is there a reason you removed the (`parser.add_mutually_exclusive_group`)[https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.add_mutually_exclusive_group]? You wouldn't need to do validation later down;
  * The above also breaks the `-f` (`--file`) option because `argparse` still requires `text` even though that's not necessary when using `-f` (again the `add_mutually_exclusive_group` took care of this);

* Wouldn't doing a `print('writing to buffer')` just before writing to `stdout` pollute your `stdout`? (and same for the unnecessary `print(args)`)

Thanks!

**Comment by Dr-Horv** [comment]
@pndurette Ah you're certainly right. Leaving the print there was a silly mistake on my part.

I also figured how to use positional argument and have them being optional. Updated the code accordingly.

**Comment by pndurette** [comment]
@Dr-Horv Thank you! Great. Nice use of Python 3's `print` for `sys.stderr` too! I will test, merge and release in the coming days.

**Comment by Dr-Horv** [comment]
@pndurette Ah thank you. Happy to help.

**Comment by Dr-Horv** [comment]
@pndurette How is this coming along? Would prefer to not use my own forked version in another project asap. :)

**Comment by pndurette** [comment]
Sorry @Dr-Horv, been pretty busy! Merged, will publish a new package.

**Comment by pndurette** [comment]
Pushed [https://pypi.python.org/pypi/gTTS/1.0.7](v.1.0.7). Thanks!

**Comment by Dr-Horv** [comment]
:smile:

**Pull request merged**
