### PR TITLE
Added setters for speed and language and say functionality

### PR DESCRIPTION
**Pull request by Tuckle**
I refactor the code a bit and added setters for speed and language so it would be possible to change talk speed and language and still have only one instance of the gtts object. I also added a function **say** to be able to just output to normal audio stream the wanted text. It makes use of playsound library which is compatible with python 2 and 3.

### CODE REVIEW

**Comment by pndurette** [comment]
Ohhh, thanks a lot for this. Let me look at this more closely. 

--
Pierre Nick Durette

**Comment by Tuckle** [comment]
So.. have you looked at it? Can you give me a feedback on that, this is like literally the first time I try something like this, so I don't really know what and how should be done all of this.

**Comment by XueWei** [comment]
@Tuckle @pndurette  Did you tried to change speed faster? I tried to set speed to 1.2. but it looks the output same with speed 1.0.

**Comment by Tuckle** [comment]
@XueWei I think the upper limit is 1(is the faster it can go for some reason). If you change it to a lower number it will go slower.

**Comment by XueWei** [comment]
@Tuckle Thanks for response! Actually some language is too slow even set speed to 1.

**Comment by pndurette** [comment]
@Tuckle Sorry for the delay on this big piece of work (thank you!), combination of being away and being pretty sick. I wanted to comment a little bit on it, after work. In a nutshell, everything is great and more than appreciated! However I specifically always left out a function to 'say' (audio), as I think this should be handled by separate tools (i.e. the unix philosophy). It could possibly be a separate project that uses `gTTs`, especially if the the goal is to provide a simple command-line tool anybody without programming experience can use.

@XueWei There is only two speeds supported by the API, standard and 'slow'. The url parameter `ttsspeed` controls the speed, it works in a weird way. `ttsspeed` set to <= 0.3 is slow, > 0.3 is 'normal', the default being 1.

**Comment by scivision** [comment]
Yes even though `playsound` is pure Python hooks to existing system sound libraries, this should at most be in setup.py extras_require

Some applications just want the byte stream emitted

**Pull request closed without merging**
