### PR TITLE
add python2.7 compatibility

### PR DESCRIPTION
**Pull request by treymarc**
fix for https://github.com/pndurette/gTTS/issues/254

try python3 and fallback to python2

pytest should pass, lets see

### CODE REVIEW

**Comment by pndurette** [comment]
Thanks for this! Not everyone wants to touch 2.7 these days.
Typically I would say screw 2.7, but this is a neat quick fix until 2.7 support is officially gone in gTTS (which it wasn't so I feel I have the obligation to make it work for at least the next release).

One thing, do you mind adding `2.x` to the testing matrix in: https://github.com/pndurette/gTTS/blob/master/.github/workflows/test.yml#L19

See if that passes?

**Comment by treymarc** [comment]
test are borken wirh python2.7 as they requires pytest>=6.1 :(

**Comment by MarcTreySonos** [comment]
testing this code with python2.7 is working 

    from gtts import gTTS
    tts = gTTS('hello')
    tts.save('hello.mp3')

**Comment by pndurette** [comment]
Alright thanks @treymarc / @MarcTreySonos!

We're already doing a big favour to the world by releasing an update for a 2.7 package. I did update `pytest` for no real reason other than it was old, it could most likely be downgraded back to the last 2.7 version `4.6.11`. 

Let me build do something I haven't done in a while, build a 2.8 virtualenv to try that out.

**Review by pndurette — COMMENTED** [review]
Ah you forgot to change it here as well:
https://github.com/pndurette/gTTS/blob/master/setup.cfg#L44

**Comment by pndurette** [comment]
Amazing, looks like Python 2.7 is back in business, against all odds. Thank you so much!

**Comment by pndurette** [comment]
Will release this shortly!

**Comment by treymarc** [comment]
thank you 👌

**Pull request merged**
