### PR TITLE
server is a parameter

### PR DESCRIPTION
**Pull request by scivision**
vis #143

### CODE REVIEW

**Comment by scivision** [comment]
This is not perhaps the most elegant way either. I just took a crack at it for fun.

**Comment by pndurette** [comment]
TIL about the `.invalid` TLD. Thanks for poking at it, and yeah, I guess that's how I was seeing it too. I somehow hate making it so couple, but I guess considering `tts` and `lang` both query the same URL.

**Comment by scivision** [comment]
Maybe this is just for future reference.

**Comment by pndurette** [comment]
@scivision Oh that’s why I was keeping it there! 😄 It’s a very good contribution, I just wasn’t sure I want to go to such length for such a feature, trickling it gown everywhere. But something like this will still happen..

**Pull request closed without merging**
