### PR TITLE
Create accents.py

### PR DESCRIPTION
**Pull request by Naman23-coder**
I was making this for my project so thought to contribute, I want to ask that should I change `accents` to `domains` or it is ok?

### CODE REVIEW

**Comment by pndurette** [comment]
Oh cool! That's a useful list! Did you try them all?

**Comment by Naman23-coder** [comment]
@pndurette it is running in backround

**Comment by Naman23-coder** [comment]
i have removed `ai` as it is not working

**Comment by Naman23-coder** [comment]
almost 95% are working

**Comment by pndurette** [comment]
Sorry for the delay on this! Thanks, this might become useful!

**Pull request merged**
