### PR TITLE
Added play sound support 

### PR DESCRIPTION
**Pull request by hawkab**
Using IPython library

### CODE REVIEW

**Comment by pndurette** [comment]
Hey @hawkab, thanks for this, let me take a look at it! Might take a few days (also I need to rework those tests, not your fault).

**Comment by MikeyBeez** [comment]
I've switched from sox to mpg123.  It just works better.

**Comment by amcareem** [comment]
How about


from IPython.display import HTML
from base64 import b64encode

path_to_audio = "/define/your/audio/path.mp3"
audio_type = "whats ur audio type? in my case its mp3"

sound = open(path_to_audio, "rb").read()
sound_encoded = **_b64encode(sound)_**
sound_tag = """
    <audio id="  **_Type yours_**  " controls src="data:audio/{1};base64,{0}">
    </audio>""".format(sound_encoded, audio_type)

play_beep = """
<script type="text/javascript">
    var audio = document.getElementById("beep");
    audio.play();
</script>
"""
Type the rest

HTML(sound_tag)

Does it help?

**Comment by pndurette** [comment]
Sorry, I'm super late to this! I appreciate the example, but I've decided that this library should remain focused on what it does. It shouldn't prescribe what to use to play sound.

**Pull request closed without merging**
