### PR TITLE
cleanup travis.yml, setup.py, README.md=>.rst, cleaner input sanitization

### PR DESCRIPTION
**Pull request by scivision**
PyPi needs RST not Markdown, or the long_description shows up as garbled text.

### CODE REVIEW

**Comment by scivision** [comment]
The Travis-CI failures were all due to zh-yue not being found. 
Has Google Speech API changed language codes?
https://cloud.google.com/speech/docs/languages

**Comment by pndurette** [comment]
Making the Readme in RST for PyPi was on my list, thank you so much for this! 
And same for the fixes to `.travis.yml` and `setup.py`. Two files that have mostly just been "set it and forget it". 

And yes, Google removed Cantonese. The voices used in `gTTS` aren't the same used by Google's public speech api. Google Translate might uses it in the background, but it has its own endpoint and list of voices, which is what this lib uses.

That being said, I'm working on `2.0.0` and I've re-written a few things, including a submodule that automatically scrapes the available languages, so there's no need to provide (and update!) a list in this lib itself.

**Comment by pndurette** [comment]
@mdiller This weekend! Wrapping up documentation, pretty much.

**Comment by pndurette** [comment]
@mdiller it’s out! 😄

**Comment by mdiller** [comment]
Cool, thanks for letting me know!

**Pull request merged**
