### PR TITLE
Add Hebrew Language

### PR DESCRIPTION
**Pull request by leranp**

### CODE REVIEW

**Comment by pndurette** [comment]
Oh nice find! However the language code for Hebrew looks to be `iw` so the tests are failing.
Do you mind adding it to the file, i.e.
```diff
     "it": "Italian",
+    "iw": "Hebrew",
     "ja": "Japanese",
```
Instead? Then I'll merge and carve a new release.
Thanks!

**Comment by leranp** [comment]
Please add this commit 👍

**Comment by leranp** [comment]
@pndurette  Thanks for the merged , can you please release a new version , i want to add it to Home Assistant

**Comment by pndurette** [comment]
Will do today! I see there's other new languages too, will release at once.

**Comment by pndurette** [comment]
@leranp Update—I didn't take the time unfortunately, I'm in the middle of a move, apologies about that! Before next week I should be able to.

**Comment by leranp** [comment]
> @leranp Update—I didn't take the time unfortunately, I'm in the middle of a move, apologies about that! Before next week I should be able to.
Hi
any news about the new release ?

**Comment by Idan37S** [comment]
Looking forward for the new release with this commit.
Any estimation on the release date?

**Comment by pndurette** [comment]
@leranp: thanks so much for your patience—
Released in `gTTS 2.2.4`! cc: @Idan37S

**Pull request merged**
